### ISSUE TITLE
Evaluation Process for Event Extraction from MAVEN Dataset

### ISSUE THREAD

**Issue by MoJa-Ardestani** [zjunlp/AutoKG#3]
Hello,

I have a question regarding your evaluation process for Event extraction from the MAVEN dataset. I was unable to locate any code detailing your approach.

For instance, in your one-shot prompt:

Given a sentence: "Unprepared for the attack, the Swedish attempted to save their ships by cutting their anchor ropes and to flee."
Event types: Removing, Rescuing, Escaping, Attack, Self-motion

You are seeking event types as listed above. My question pertains to how you calculate the F1 score for a LLM when some data samples contain one event per sentence while others contain multiple events within a sentence. Could you please elucidate how you calculate precision and recall for each sample and overall for a model?

Thank you.

**Comment by LesileZ** [comment]
Hello, thank you for your question. 
For evaluating event extraction from the MAVEN dataset with varying numbers of events per sentence, we use the micro F1 scoring method.  This aligns with the evaluation script found at https://github.com/THU-KEG/MAVEN-dataset/blob/main/evaluate.py.
 By aggregating true positives, false positives, and false negatives across all sentences in the testing set, we compute the overall precision and recall. The micro F1 score is subsequently calculated from these aggregated values, ensuring a fair evaluation across different event densities in sentences.

**Comment by MoJa-Ardestani** [comment]
Thank you for your prompt response. I also have a question regarding the evaluation of "Entity and Relation Extraction," illustrated through the following example:

Example:
The provided sentence is: "We show that various features based on the structure of email-threads can be used to improve upon lexical similarity of discourse segments for question-answer pairing."
Triples: [lexical similarity, FEATURE-OF, discourse segments]

If our Language Model returns two triples (one matching the ground truth and another not matching) for the given sentence, should we calculate the F1 score as you mentioned for event extraction? Or should we consider the output of the Language Model containing the correct triple as one true prediction and ignore any extra predicted triples for the given sentence?

**Comment by LesileZ** [comment]
Thank you for your follow-up question. Indeed, for "Entity and Relation Extraction", you could calculate the F1 score in the same way as for event extraction, taking into account both correct and incorrect triples generated by the Language Model during evaluation.

**Comment by MoJa-Ardestani** [comment]
Thank you for your prompt response. Would you be able to share the evaluation scripts for the SciERC and Re-TACRED datasets? Additionally, including some sample model predictions that are compatible with these scripts would be immensely helpful. Thank you sincerely.

**Comment by LesileZ** [comment]
Thank you for your inquiry. Given the limited volume of data in our experiments and to streamline the analysis process, we have opted for manual computation to conduct relevant data statistics and evaluations, rather than relying on scripts. This approach guarantees higher accuracy, as larger models often produce irrelevant information other than the correct answer. For guidance on calculating the F1 score, please refer to our prior communication. Alternatively, you can visit  https://github.com/THU-KEG/MAVEN-dataset/blob/main/evaluate.py to develop your own script.  We hope this information proves helpful.

**Comment by MoJa-Ardestani** [comment]
Thank you for your quick response and the provided information.
I managed to review the evaluation of the MAVEN dataset based on the link you shared, and I appreciate it.

To ensure that I understand the concept of measuring F1  for Triple Extraction (SciERC dataset) as you mentioned, could you please confirm the following example: We have two fictitious sample data points in our example identified with ids:

Model Prediction: 
{'id': 0, 'Triples': [['outlier removal', 'PART-OF', 'stereo vision'], ['detection task', 'EVALUATE-FOR', 'our algorithm'] ]},
{'id': 1, 'Triples': [['detection task', 'EVALUATE-FOR', 'our algorithm'],  ['viewpoint classification task', 'EVALUATE-FOR', 'our algorithm'], ['detection task', 'CONJUNCTION', 'viewpoint classification task'] ]}

Ground truth:
{'id': 0, 'Triples': ['outlier removal', 'PART-OF', 'stereo vision']}
{'id': 1, 'Triples': ['detection task', 'CONJUNCTION', 'viewpoint classification task']}

As it's evident, our model predicted 5 triples for these two sample sentences, of which only two match the ground truth. In this scenario, based on your evaluation method, is the precision 2/5, and is the recall 2/2?

Regarding certain relations, does the order of the triple matter for all relations?

['COMPARE', 'HYPONYM-OF', 'PART-OF', 'FEATURE-OF', 'USED-FOR', 'CONJUNCTION', 'EVALUATE-FOR']

For instance, for the CONJUNCTION relation, the order of the head and tail is not meaningful to me.

Have you taken into account the order of triples for all relation classes in your evaluation?

**Comment by LesileZ** [comment]
Thank you for your question. 
Your calculations for precision and recall are correct based on your example. It's important to note that the order of entities in a triple matters for most relations, but not for all, like CONJUNCTION where the order doesn't change the meaning. In our evaluations, we follow the dataset's ground truth, meaning we don't always consider the order of entities. For more detailed information, you can check the methodology used in the Re-TACRED project at this link: https://github.com/gstoica27/Re-TACRED/blob/master/SpanBERT/run_tacred.py.
