### ISSUE TITLE
知识图谱构建效果

### ISSUE THREAD

**Issue by wujiaxin-study** [zjunlp/AutoKG#5]
运行了autokg代码  如果我有一个文档（包含很多段文字） 构建对应知识图谱 （不需要外部信息）如何实现？  我运行的结果是几段对话 而并不是三元组

**Comment by zxlzr** [comment]
您好，有文档的话和目前我们实验设定是不一样的，建议您尝试不同的prompt，并使用信息抽取技术抽取文档的实体和关系来构建知识图谱。

**Comment by zxlzr** [comment]
请问您还有其它问题吗？

**Comment by wujiaxin-study** [comment]
您好  非常感谢您的回复 暂时没有问题了
