### ISSUE TITLE
AutoKG部分代码运行效果

### ISSUE THREAD

**Issue by pingzi777** [zjunlp/AutoKG#6]
在运行Auto KG部分代码之后，输出的结果是对搜索结果的提纯，并不是论文中示例的样子
"Spider-Ham is a fictional character from an alternate dimension in the Marvel Comics universe. He is a pig who gained spider-like abilities after being bitten by a radioactive spider. He has appeared in various media, including comics, TV shows, and movies."
原文中的例子是经过后期的构建和推理得出来的么，还是我这里代码运行不完整

另在测试过程中，会出现跑题，生成与电影本身关系不大的内容，比如“Solution: I have incorporated a node for the animation style "2D Hand-Drawn Animation" in the Knowledge Graph, including characteristics and examples of this animation style”
不知贵团队有没有干预这种情况

祝科研工作和生活顺利！！！
[111.pdf](https://github.com/user-attachments/files/17355604/111.pdf)

**Comment by LesileZ** [comment]
我们在实验的时候确实没有遇见过这种问题，只是对输出的内容整理即可。猜测可能是camel或者是gpt api版本更新的原因，或许可以通过修改CAMELAgent对应的参数来改进效果？

**Comment by pingzi777** [comment]
好的，谢谢！
